ARG BASE_IMAGE_TAG=latest
FROM reactnativecommunity/react-native-android:${BASE_IMAGE_TAG}

ENV DEBIAN_FRONTEND=noninteractive 

ARG ROOT_PASS
ARG LLVM_VERSION=14
ARG USER_NAME
ARG USER_GROUP
ARG USER_PASS
ARG USER_ID
ARG GROUP_ID
ARG USER_HOME=/home/$USER_NAME

RUN for arg in ROOT_PASS USER_NAME USER_GROUP USER_PASS USER_ID GROUP_ID; \
  do \
  [ ! -z "${arg}" ] || { echo "ARG \"$arg\" needs to be set"; exit 1; } \
  done;

RUN echo "root:$ROOT_PASS" | chpasswd

RUN npm install -g n
RUN n stable

# TODO add a step for trusting github cli download repo. 
# otherwise it's causing errors in devcontainers
RUN sudo apt-get update && \
  apt-get upgrade -y && \
  sudo apt-get install -y \
  lsb-release \
  wget \
  software-properties-common \
  apt-utils
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
RUN sudo add-apt-repository -y \
  "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${LLVM_VERSION} main"
RUN apt-get autoremove -y \
  software-properties-common \
  apt-utils 

RUN apt-get update && \
  apt-get install -y \
  clang-${LLVM_VERSION} \
  lldb-${LLVM_VERSION} \
  lld-${LLVM_VERSION} \
  ccache 

# Neovim requires manual retrieval of the latest version
# as the apt package is quite old
RUN wget https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb \
  -O /neovim.deb
RUN apt install -y /neovim.deb 
RUN rm /neovim.deb
ENV EDITOR=nvim

RUN groupadd -g ${USER_ID} ${USER_GROUP}
RUN useradd -m -u ${USER_ID} -g ${GROUP_ID} ${USER_NAME} -s /bin/bash
RUN bash -c "chpasswd <<< \"${USER_NAME}:${USER_PASS}\""
RUN usermod -aG sudo ${USER_NAME}

# Gists
ADD --chown=${USER_ID}:${GROUP_ID} \
  https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/create-env-example.sh \
  /scripts/create-env-example.sh

ADD --chown=${USER_ID}:${GROUP_ID} \
  https://gist.githubusercontent.com/utkusarioglu/3523b00578807d63b05399fe57a4b2a7/raw/.bashrc \
  ${USER_HOME}/.bashrc
ADD --chown=${USER_ID}:${GROUP_ID} \
  https://gist.githubusercontent.com/utkusarioglu/d5c216c744460c45bf6260d0de4131b4/raw/.inputrc \
  /home/${USER_NAME}/.inputrc
RUN cp ${USER_HOME}/.bashrc /root/.bashrc
RUN cp ${USER_HOME}/.inputrc /root/.inputrc

COPY src/scripts /scripts
COPY scripts/ln-ccache.sh /scripts/ln-ccache.sh
RUN chmod +x /scripts/*

# Linking compiler caches
# env is going to be read by ccache, the same path shall be mounted on the
# devcontainer for this to work
ENV CCACHE_DIR=/ccache 
RUN /scripts/ln-ccache.sh 

USER ${USER_NAME}

# These are here to prevent these folders from being mounted as root
RUN mkdir -p ${USER_HOME}/.vscode-server/extensions
RUN mkdir -p ${USER_HOME}/.vscode-server-insiders/extensions
RUN mkdir -p ${USER_HOME}/.gradle
RUN mkdir -p /opt/android
