name: Build and push

on:
  workflow_call:
    inputs: 
      image_tag:
        description: Tag of the final docker image
        type: string
        required: true
      base_tag:
        description: Ubuntu base image tag
        type: string
        required: true
    secrets:
      dockerhub_username: 
        required: true
      dockerhub_token: 
        required: true 

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        images:
          - image_name: react-native-android-devcontainer
            base_image: node-devcontainer
            base_tag: ${{ inputs.base_tag }}
            image_tag: ${{ inputs.image_tag }}
          
            # https://developer.android.com/studio#command-line-tools-only
            # sdk_version: commandlinetools-linux-11076708_latest.zip
            sdk_version: commandlinetools-linux-13114758_latest.zip

            # https://developer.android.com/tools/releases/platforms
            android_platform_version: 36
            android_build_tools_version: 36.0.0

            # https://groups.google.com/g/android-ndk-announce
            # ndk_version: 29.0.13113456
            ndk_version: 29.0.13599879

            # cmake_version: 3.31.6
            cmake_version: 4.1.0

            docker_context: src
            dockerfile_path: src/Dockerfile.android.dev
            devcontainer_run_cmd_path: /home/dev/scripts/bootstrap/node/check-devcontainer.sh
            dockerhub_repo_readme_file_path: src/DOCKER_README.md
            devcontainer_subfolder: src
            apt_packages: ""
              
            # Dev libraries requested by Hermes
            # libicu-dev
            # Dev dependencies required by linters
            # shellcheck
            apt_packages_silent: >-
              apt-transport-https
              file
              gcc
              g++
              gnupg2
              libgl1
              libtcmalloc-minimal4
              make
              openjdk-17-jdk-headless
              openssh-client
              patch
              python3
              ruby
              ruby-dev
              tzdata
              sudo
              ninja-build
              zip
              ccache
              libicu-dev
              shellcheck
              ccache
              clang-18
              lldb-18
              lld-18

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: utkusarioglu/devcontainer-build@main
        with:
          docker_context: ${{ matrix.images.docker_context }}
          dockerhub_username: ${{ secrets.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          image_name: ${{ matrix.images.image_name }}
          image_tag: ${{ matrix.images.image_tag }}
          dockerfile_path: ${{ matrix.images.dockerfile_path }}
          build_args: |
            BASE_IMAGE=${{ matrix.images.base_image }}
            BASE_TAG=${{ matrix.images.base_tag }}
            APT_PACKAGES=${{ matrix.images.apt_packages }}
            APT_PACKAGES_SILENT=${{ matrix.images.apt_packages_silent }}
            SDK_VERSION=${{ matrix.images.sdk_version}}
            ANDROID_PLATFORM_VERSION=${{ matrix.images.android_platform_version }}
            ANDROID_BUILD_TOOLS_VERSION=${{ matrix.images.android_build_tools_version }}
            NDK_VERSION=${{ matrix.images.ndk_version }}
            CMAKE_VERSION=${{ matrix.images.cmake_version }}
          devcontainer_enabled: "false"
          devcontainer_subfolder: ${{ matrix.images.devcontainer_subfolder }}
          devcontainer_run_cmd_path: ${{ matrix.images.devcontainer_run_cmd_path }}
          dockerhub_repo_short_description: NodeJS devcontainers
          dockerhub_repo_readme_file_path: ${{ matrix.images.dockerhub_repo_readme_file_path }}
