name: Push

on:
  push
  
concurrency:
  cancel-in-progress: true
  group: push

jobs:
  push:
    uses: ./.github/workflows/build.wfc.yml
    with:
      image_tag: 36-24-ubuntu-test-27
      
      # https://hub.docker.com/repository/docker/utkusarioglu/node-devcontainer/tags
      base_tag: 24-ubuntu-test-27
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    