name: Push

on:
  push
  
concurrency:
  cancel-in-progress: true
  group: push

jobs:
  push:
    uses: ./.github/workflows/build.wfc.yml
    with:
      image_tag: 35-23-ubuntu-test-26
      base_tag: 23-ubuntu-test-26
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    